// Auto-generated by LibreLane
module single_cycle_cpu(
`ifdef USE_POWER_PINS
  inout VGND,
  inout VPWR,
`endif
  input clk,
  input reset,
  output[31:0] pc_out,
  output[31:0] instruction_out,
  output[31:0] alu_result_out
);
endmodule
